version: '3'

volumes:
  pgdata:
    driver: local
  indexdata:
    driver: local
  dbdump:
    driver: local

services:
  db:
    build:
      context: postgres-dockerfile
      args:
        - POSTGRES_VERSION=${POSTGRES_VERSION:-9.5}
    image: musicbrainz-docker_db:${POSTGRES_VERSION:-9.5}
    restart: unless-stopped
    env_file:
      - ./postgres-dockerfile/postgres.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    expose:
      - "5432"

  musicbrainz:
    build:
      context: musicbrainz-dockerfile
      args:
        - POSTGRES_VERSION=${POSTGRES_VERSION:-9.5}
    ports:
      - "5000:5000"
    volumes:
      - dbdump:/media/dbdump
    restart: unless-stopped
    env_file:
      - ./postgres-dockerfile/postgres.env
    environment:
      - MUSICBRAINZ_USE_PROXY=1
    depends_on:
      - db
      - search
      - redis

  indexer:
    build: indexer-dockerfile
    depends_on:
      - db
    volumes:
      - indexdata:/home/search/indexdata

  search:
    build: search-dockerfile
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - indexdata:/home/search/indexdata

  redis:
    image: redis:3-alpine
    restart: unless-stopped
    expose:
      - "6379"
